// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRABALHO_VOLVO;

#nullable disable

namespace TRABALHO_volvo.Migrations
{
    [DbContext(typeof(TrabalhoVolvoContext))]
    [Migration("20240207021511_CreateDatabase4")]
    partial class CreateDatabase4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TRABALHO_VOLVO.Caminhao", b =>
                {
                    b.Property<int>("CodCaminhao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCaminhao"));

                    b.Property<bool>("CaminhaoAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("CodChassiCaminhao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorCaminhao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataFabricacao")
                        .HasColumnType("date");

                    b.Property<int>("FkClientesCodCliente")
                        .HasColumnType("int");

                    b.Property<int>("FkModelosCaminhoesCodModelo")
                        .HasColumnType("int");

                    b.Property<string>("PlacaCaminhao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quilometragem")
                        .HasColumnType("float");

                    b.HasKey("CodCaminhao");

                    b.HasIndex("CodChassiCaminhao")
                        .IsUnique();

                    b.ToTable("Caminhoes");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.CaminhaoEstoque", b =>
                {
                    b.Property<int>("CodCaminhaoEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCaminhaoEstoque"));

                    b.Property<bool>("CaminhaoEstoqueAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("CodChassiEstoque")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorEstoqueCaminhao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DataFabricacao")
                        .HasColumnType("date");

                    b.Property<int>("FkConcessionariasCodConc")
                        .HasColumnType("int");

                    b.Property<int>("FkModelosCaminhoesCodModelo")
                        .HasColumnType("int");

                    b.HasKey("CodCaminhaoEstoque");

                    b.HasIndex("CodChassiEstoque")
                        .IsUnique();

                    b.ToTable("EstoqueCaminhao");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.Cargo", b =>
                {
                    b.Property<int>("CodCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCargo"));

                    b.Property<bool>("CargoAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("NomeCargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("PorcentagemComissao")
                        .HasColumnType("float");

                    b.Property<double>("SalarioBase")
                        .HasColumnType("float");

                    b.HasKey("CodCargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.Cliente", b =>
                {
                    b.Property<int>("CodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodCliente"));

                    b.Property<bool>("ClienteAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("DocIdentificadorCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EmailCliente")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroContatoCliente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CodCliente");

                    b.HasIndex("DocIdentificadorCliente")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.Concessionaria", b =>
                {
                    b.Property<int>("CodConc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodConc"));

                    b.Property<string>("CepConcessionaria")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("ConcessionariaAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomeConc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CodConc");

                    b.HasIndex("CepConcessionaria")
                        .IsUnique();

                    b.ToTable("Concessionarias");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.Funcionario", b =>
                {
                    b.Property<int>("CodFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodFuncionario"));

                    b.Property<string>("CpfFuncionario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("FkCargosCodCargo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("FkConcessionariasCodConc")
                        .HasColumnType("int");

                    b.Property<bool>("FuncionarioAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroContatoFuncionario")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CodFuncionario");

                    b.HasIndex("CpfFuncionario")
                        .IsUnique();

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.ModelosCaminhao", b =>
                {
                    b.Property<int>("CodModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodModelo"));

                    b.Property<bool>("ModelosAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("ValorModeloCaminhao")
                        .HasColumnType("float");

                    b.HasKey("CodModelo");

                    b.ToTable("ModelosCaminhoes");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.PecaEstoque", b =>
                {
                    b.Property<int>("CodPecaEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPecaEstoque"));

                    b.Property<DateOnly>("DataFabricacao")
                        .HasColumnType("date");

                    b.Property<int>("FkConcessionariasCodConc")
                        .HasColumnType("int");

                    b.Property<int>("FkTiposPecaCodTipoPeca")
                        .HasColumnType("int");

                    b.Property<bool>("PecaEstoqueAtiva")
                        .HasColumnType("bit");

                    b.HasKey("CodPecaEstoque");

                    b.ToTable("EstoquePecas");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.ServicoManutencao", b =>
                {
                    b.Property<int>("CodManutencao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodManutencao"));

                    b.Property<DateTime>("DataManutencao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoManutencao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("FkCaminhoesCodCaminhao")
                        .HasColumnType("int");

                    b.Property<int>("FkConcessionariasCodConc")
                        .HasColumnType("int");

                    b.Property<int>("FkFuncionariosCodFuncionario")
                        .HasColumnType("int");

                    b.Property<double>("QuilometragemCaminhao")
                        .HasColumnType("float");

                    b.Property<double>("ValorServicoManutencao")
                        .HasColumnType("float");

                    b.HasKey("CodManutencao");

                    b.ToTable("ServicosManutencao");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.ServicoTipoPeca", b =>
                {
                    b.Property<int>("CodServicoTipoPeca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodServicoTipoPeca"));

                    b.Property<int>("FkCodManutencao")
                        .HasColumnType("int");

                    b.Property<int>("FkTiposPecaCodTipoPeca")
                        .HasColumnType("int");

                    b.HasKey("CodServicoTipoPeca");

                    b.ToTable("ServicoTiposPeca");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.TipoPeca", b =>
                {
                    b.Property<int>("CodTipoPeca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTipoPeca"));

                    b.Property<string>("NomeTipoPeca")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("PecaAtivo")
                        .HasColumnType("bit");

                    b.Property<double>("ValorTipoPeca")
                        .HasColumnType("float");

                    b.HasKey("CodTipoPeca");

                    b.ToTable("TiposPeca");
                });

            modelBuilder.Entity("TRABALHO_VOLVO.VendaCaminhao", b =>
                {
                    b.Property<int>("CodVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodVenda"));

                    b.Property<DateOnly>("DataVenda")
                        .HasColumnType("date");

                    b.Property<int>("FkClientesCodCliente")
                        .HasColumnType("int");

                    b.Property<int>("FkConcessionariasCodConc")
                        .HasColumnType("int");

                    b.Property<int>("FkEstoqueCaminhoesCodCaminhaoEstoque")
                        .HasColumnType("int");

                    b.Property<int>("FkFuncionariosCodFuncionario")
                        .HasColumnType("int");

                    b.Property<double>("ValorVenda")
                        .HasColumnType("float");

                    b.HasKey("CodVenda");

                    b.ToTable("VendaCaminhoes");
                });
#pragma warning restore 612, 618
        }
    }
}
